import { generatePageMetadata } from '@/lib/metadata';
import Hero from '@/components/sections/Hero';
import PainPoints from '@/components/sections/PainPoints';
import WorkflowDetail from '@/components/sections/WorkflowDetail';
import ROISummary from '@/components/sections/ROISummary';
import CTASection from '@/components/sections/CTASection';
import { ArrowRight } from 'lucide-react';
import Link from 'next/link';

export const metadata = generatePageMetadata({
  title: 'AI Automation for Recruitment Agencies | Workflow Solutions',
  description:
    'Automate candidate sourcing, screening, scheduling, and reporting for recruitment agencies. Save 40+ hours/week with custom AI workflows.',
  path: '/industries/recruitment',
});

const painPoints = [
  'Recruiters spend 60%+ of their time on non-revenue tasks',
  'Candidate screening is manual, slow, and inconsistent',
  'Interview scheduling involves endless email chains',
  'Client reporting is assembled manually every week or month',
  'Top candidates slip through because follow-up is delayed',
  'CRM and ATS data is messy, duplicated, and underused',
];

const workflows = [
  {
    title: 'AI-Powered Candidate Sourcing & Screening',
    problem:
      'Recruiters manually search job boards, LinkedIn, and databases — spending hours finding candidates that may not even be a fit.',
    steps: [
      'Job requirement is posted or updated in your ATS/CRM',
      'AI agent scrapes and aggregates candidates from LinkedIn, job boards, and internal databases',
      'LLM scores each candidate against role requirements (skills match, experience, location, salary expectations)',
      'Top-ranked candidates are automatically pushed to a shortlist in your ATS with a fit-score and summary',
    ],
    tools: ['n8n/Make', 'LLM (GPT-4/Claude)', 'LinkedIn API', 'ATS Integration (Bullhorn, JobAdder, Vincere)'],
    outcome:
      '80% reduction in initial sourcing time. Recruiters receive pre-qualified shortlists within hours, not days.',
  },
  {
    title: 'Automated Interview Scheduling & Follow-Ups',
    problem:
      'Coordinating interview times between candidates, recruiters, and clients involves dozens of back-and-forth emails.',
    steps: [
      'Candidate reaches the "interview" stage in ATS',
      'AI checks calendar availability of interviewer(s) and candidate',
      'Sends scheduling link or proposes times automatically via email/SMS',
      'Confirmation, reminders (24hr + 1hr), and follow-up (post-interview feedback request) are sent automatically',
    ],
    tools: ['n8n/Make', 'Google Calendar/Outlook API', 'Email/SMS Integration', 'ATS Webhook'],
    outcome:
      'Zero manual scheduling. 95% reduction in no-shows due to automated reminders.',
  },
  {
    title: 'Client Reporting & Pipeline Dashboards',
    problem:
      'Agencies spend hours each week compiling placement data, pipeline metrics, and status updates for clients.',
    steps: [
      'Data is pulled automatically from ATS/CRM (active roles, candidate pipeline, interview stages, placements)',
      'LLM generates a narrative summary of weekly/monthly activity',
      'Dashboard is auto-updated with real-time metrics (time-to-fill, submission-to-interview ratio, placement rate)',
      'Branded PDF report is generated and emailed to clients on schedule',
    ],
    tools: ['n8n/Make', 'ATS API', 'LLM', 'Google Sheets/Airtable', 'PDF Generation', 'Email'],
    outcome:
      'Client reports delivered in minutes, not hours. Real-time dashboards build client trust and retention.',
  },
  {
    title: 'Candidate Engagement & Nurture Sequences',
    problem:
      'Great candidates go cold because agencies don\'t have the bandwidth for consistent follow-up.',
    steps: [
      'Candidates not placed are tagged and segmented in CRM',
      'Automated nurture sequences fire based on segment (e.g., "available in 30 days," "passive but open")',
      'Personalised emails/messages are generated by LLM based on candidate profile and recent job openings',
      'Re-engagement triggers when a matching role opens',
    ],
    tools: ['n8n/Make', 'CRM', 'LLM', 'Email Automation'],
    outcome:
      '3x increase in candidate re-engagement. Passive talent pool stays warm without recruiter effort.',
  },
  {
    title: 'Job Description & Posting Automation',
    problem:
      'Writing job descriptions and posting across multiple boards is repetitive and time-consuming.',
    steps: [
      'Recruiter inputs key role details (title, requirements, salary band, client)',
      'LLM generates an optimised job description (SEO-friendly, inclusive language, brand-consistent)',
      'JD is automatically posted to selected job boards (Indeed, Reed, Totaljobs, LinkedIn)',
      'Performance tracking aggregates applicant data back into the ATS',
    ],
    tools: ['n8n/Make', 'LLM', 'Job Board APIs', 'ATS Integration'],
    outcome: 'Job descriptions created in 2 minutes. Multi-board posting in one click.',
  },
  {
    title: 'Compliance & Document Automation',
    problem:
      'Recruitment agencies must manage contracts, right-to-work checks, GDPR consent, and onboarding documents — all manually.',
    steps: [
      'Candidate reaches "offer" stage',
      'AI generates personalised contract/offer letter from templates',
      'Right-to-work document checklist is sent to candidate with upload portal',
      'GDPR consent forms are auto-generated and tracked',
      'All documents are filed automatically in the candidate record',
    ],
    tools: ['n8n/Make', 'Document Generation (DocuSign/PandaDoc)', 'Cloud Storage', 'ATS'],
    outcome:
      '90% reduction in onboarding admin. Full compliance audit trail maintained automatically.',
  },
];

const roiMetrics = [
  { label: 'Admin Hours/Week', before: '25 hrs', after: '4 hrs' },
  { label: 'Time to Shortlist', before: '3 days', after: '4 hours' },
  { label: 'Client Reporting', before: 'Manual weekly', after: 'Automated real-time' },
];

export default function RecruitmentPage() {
  return (
    <>
      <Hero
        headline="AI Automation for Recruitment Agencies"
        subheadline="Stop losing placements to admin. We automate candidate sourcing, screening, scheduling, and reporting — so your recruiters focus on relationships, not repetition."
        primaryCTA={{ label: 'Book Your Recruitment Automation Audit', href: '/contact' }}
        showWorkflow
      />

      <PainPoints
        title="The Recruitment Agency Bottleneck"
        points={painPoints}
      />

      <section className="relative py-24 lg:py-32">
        <div className="mx-auto max-w-7xl px-6">
          <div className="text-center mb-16">
            <h2 className="text-3xl lg:text-4xl font-bold font-heading text-white mb-4">
              6 AI Workflows That Transform Recruitment Operations
            </h2>
            <p className="text-lg text-text-secondary font-body max-w-2xl mx-auto">
              Purpose-built automations that address your specific pain points — from
              sourcing to placement and everything in between.
            </p>
          </div>

          <div className="grid gap-8">
            {workflows.map((workflow, index) => (
              <WorkflowDetail
                key={workflow.title}
                index={index + 1}
                title={workflow.title}
                problem={workflow.problem}
                steps={workflow.steps}
                tools={workflow.tools}
                outcome={workflow.outcome}
              />
            ))}
          </div>
        </div>
      </section>

      <ROISummary metrics={roiMetrics} />

      <CTASection
        headline="Your Recruiters Should Be Placing, Not Processing. Let's Automate the Rest."
        subtext="Book a free 30-minute automation audit. We'll map your recruitment workflows and show you exactly where AI can save time and money."
        buttonLabel="Book Your Free Recruitment Audit →"
        buttonHref="/contact"
      />
    </>
  );
}
